- name: Install SSH Keys
  run: |
    mkdir -p ~/.ssh
    install -m 600 -D /dev/null ~/.ssh/id_rsa
    echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -p 2323 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
